// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuzsKZ54VcxhKrjpJhWtPtRYE4S6q7Ff4',
    appId: '1:121185837499:web:284bff41519b04694ae49e',
    messagingSenderId: '121185837499',
    projectId: 'basalon-b4710',
    authDomain: 'basalon-b4710.firebaseapp.com',
    storageBucket: 'basalon-b4710.appspot.com',
    measurementId: 'G-0F5EFX75KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPuWndJIbNyF9zxLQ424y3f6e8sr0mpI',
    appId: '1:121185837499:android:b729cd1e1a1062554ae49e',
    messagingSenderId: '121185837499',
    projectId: 'basalon-b4710',
    storageBucket: 'basalon-b4710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMzikPckeJNubVhu8Ypl0U1cdYJ-y8UZQ',
    appId: '1:121185837499:ios:e2d03abb1190eea04ae49e',
    messagingSenderId: '121185837499',
    projectId: 'basalon-b4710',
    storageBucket: 'basalon-b4710.appspot.com',
    iosClientId: '121185837499-eleb57v0kdkgeinp2ad1f48m5cs9hil1.apps.googleusercontent.com',
    iosBundleId: 'il.co.basalon',
  );
}
